python ControlledFinals/LeadershipQuest.py --head_less \
--multi_process \
--skip_avatar_animation \
--output_dir output/CF/LQ \
--challenge leadership_quest \
--scene NY \
--outdoor_objects_max_num 2 \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type optimus1 \
--max_seconds 21600 \
--save_per_seconds 10 \
--lm_id gpt-4o